defaults:
  - _self_

# Dataset configuration
dataset:
  name: ???  # Must be specified
  subset: null
  cache_dir: data/cache
  split: train

# Preprocessing configuration
preprocessing:
  transforms:
    - name: MeanScaler
      params:
        center: true
        epsilon: 1.0e-8
    - name: StandardScaler
      params:
        epsilon: 1.0e-8
    - name: MinMaxScaler
      params:
        feature_range: [0, 1]
        epsilon: 1.0e-8

# Augmentation configuration
augmentation:
  enabled: false
  methods: []
  linear_combo_ratio: 0.5
  jitter_sigma: 0.01
  time_warp_sigma: 0.1

# DataLoader configuration
dataloader:
  batch_size: 32
  num_workers: 4
  shuffle: true
  pin_memory: true 